### ISSUE TITLE
Subtitle line messes up card shape

### ISSUE THREAD

**Issue by jeff47** [walkxcode/homer-theme#10]
<img width="1270" alt="Screen Shot 2021-11-02 at 11 52 23 AM" src="https://user-images.githubusercontent.com/7215369/139886120-b99b8ee6-2831-4987-834a-0ee355d410ff.png">

Please see the attached screenshot.  (This is in Brave.)  There is a "little bump out" on the "subtitle" line for each card.

**Comment by walkxcode** [comment]
This is called a tag. This is intended. It looks like this in the official default homer theme too.

**Comment by walkxcode** [comment]
If you hover over an item you should see the tag expand and show the full tag.

**Comment by jeff47** [comment]
Got it, thanks.

**Comment by walkxcode** [comment]
No problem!
