### ISSUE TITLE
Change Color Title columns

### ISSUE THREAD

**Issue by mada199122** [walkxcode/homer-theme#7]
Hi,
thanks for your great theme;)

I would like to change the color of the title in black at least for the light version.
Is it possible?
I've attached a screen shot to explain better...

Thanks
![Uploading Screenshot 2021-10-18 at 17.42.01.jpg…]()

**Comment by mada199122** [comment]
![Screenshot 2021-10-18 at 19 03 42](https://user-images.githubusercontent.com/61902329/137776165-f53b2f1e-3432-4759-9c4a-d02b5628dcf5.jpg)

**Comment by WalkxCode** [comment]
In the config.yml change the color for `text` to any color you'd like!
